name: Lint HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run HTMLHint
        uses: reviewdog/action-htmlhint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
